api_key: API KEY LOL
leetcode_polling_interval: 900 # query LeetCode every 15 minutes
port: 8080
sqlite3_file_name: users.db
local_timezone: America/Los_Angeles

points:
  easy: 1
  medium: 3
  hard: 5
